# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-8.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-8.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-8.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lucaserickson/Desktop/PhotosFromOldCamera/antz/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lucaserickson/Desktop/PhotosFromOldCamera/antz/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-8.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-8.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucaserickson/Desktop/PhotosFromOldCamera/antz/src/CMakeFiles /Users/lucaserickson/Desktop/PhotosFromOldCamera/antz/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucaserickson/Desktop/PhotosFromOldCamera/antz/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named antz

# Build rule for target.
antz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antz
.PHONY : antz

# fast build rule for target.
antz/fast:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/build
.PHONY : antz/fast

ctrl/npcmd.o: ctrl/npcmd.c.o
.PHONY : ctrl/npcmd.o

# target to build an object file
ctrl/npcmd.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/npcmd.c.o
.PHONY : ctrl/npcmd.c.o

ctrl/npcmd.i: ctrl/npcmd.c.i
.PHONY : ctrl/npcmd.i

# target to preprocess a source file
ctrl/npcmd.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/npcmd.c.i
.PHONY : ctrl/npcmd.c.i

ctrl/npcmd.s: ctrl/npcmd.c.s
.PHONY : ctrl/npcmd.s

# target to generate assembly for a file
ctrl/npcmd.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/npcmd.c.s
.PHONY : ctrl/npcmd.c.s

ctrl/npengine.o: ctrl/npengine.c.o
.PHONY : ctrl/npengine.o

# target to build an object file
ctrl/npengine.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/npengine.c.o
.PHONY : ctrl/npengine.c.o

ctrl/npengine.i: ctrl/npengine.c.i
.PHONY : ctrl/npengine.i

# target to preprocess a source file
ctrl/npengine.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/npengine.c.i
.PHONY : ctrl/npengine.c.i

ctrl/npengine.s: ctrl/npengine.c.s
.PHONY : ctrl/npengine.s

# target to generate assembly for a file
ctrl/npengine.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/npengine.c.s
.PHONY : ctrl/npengine.c.s

ctrl/nptest.o: ctrl/nptest.c.o
.PHONY : ctrl/nptest.o

# target to build an object file
ctrl/nptest.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/nptest.c.o
.PHONY : ctrl/nptest.c.o

ctrl/nptest.i: ctrl/nptest.c.i
.PHONY : ctrl/nptest.i

# target to preprocess a source file
ctrl/nptest.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/nptest.c.i
.PHONY : ctrl/nptest.c.i

ctrl/nptest.s: ctrl/nptest.c.s
.PHONY : ctrl/nptest.s

# target to generate assembly for a file
ctrl/nptest.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/ctrl/nptest.c.s
.PHONY : ctrl/nptest.c.s

data/npmap.o: data/npmap.c.o
.PHONY : data/npmap.o

# target to build an object file
data/npmap.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npmap.c.o
.PHONY : data/npmap.c.o

data/npmap.i: data/npmap.c.i
.PHONY : data/npmap.i

# target to preprocess a source file
data/npmap.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npmap.c.i
.PHONY : data/npmap.c.i

data/npmap.s: data/npmap.c.s
.PHONY : data/npmap.s

# target to generate assembly for a file
data/npmap.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npmap.c.s
.PHONY : data/npmap.c.s

data/npmapfile.o: data/npmapfile.c.o
.PHONY : data/npmapfile.o

# target to build an object file
data/npmapfile.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npmapfile.c.o
.PHONY : data/npmapfile.c.o

data/npmapfile.i: data/npmapfile.c.i
.PHONY : data/npmapfile.i

# target to preprocess a source file
data/npmapfile.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npmapfile.c.i
.PHONY : data/npmapfile.c.i

data/npmapfile.s: data/npmapfile.c.s
.PHONY : data/npmapfile.s

# target to generate assembly for a file
data/npmapfile.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npmapfile.c.s
.PHONY : data/npmapfile.c.s

data/npnode.o: data/npnode.c.o
.PHONY : data/npnode.o

# target to build an object file
data/npnode.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npnode.c.o
.PHONY : data/npnode.c.o

data/npnode.i: data/npnode.c.i
.PHONY : data/npnode.i

# target to preprocess a source file
data/npnode.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npnode.c.i
.PHONY : data/npnode.c.i

data/npnode.s: data/npnode.c.s
.PHONY : data/npnode.s

# target to generate assembly for a file
data/npnode.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/data/npnode.c.s
.PHONY : data/npnode.c.s

io/db/npauxdb.o: io/db/npauxdb.c.o
.PHONY : io/db/npauxdb.o

# target to build an object file
io/db/npauxdb.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/db/npauxdb.c.o
.PHONY : io/db/npauxdb.c.o

io/db/npauxdb.i: io/db/npauxdb.c.i
.PHONY : io/db/npauxdb.i

# target to preprocess a source file
io/db/npauxdb.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/db/npauxdb.c.i
.PHONY : io/db/npauxdb.c.i

io/db/npauxdb.s: io/db/npauxdb.c.s
.PHONY : io/db/npauxdb.s

# target to generate assembly for a file
io/db/npauxdb.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/db/npauxdb.c.s
.PHONY : io/db/npauxdb.c.s

io/db/npmysql.o: io/db/npmysql.c.o
.PHONY : io/db/npmysql.o

# target to build an object file
io/db/npmysql.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/db/npmysql.c.o
.PHONY : io/db/npmysql.c.o

io/db/npmysql.i: io/db/npmysql.c.i
.PHONY : io/db/npmysql.i

# target to preprocess a source file
io/db/npmysql.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/db/npmysql.c.i
.PHONY : io/db/npmysql.c.i

io/db/npmysql.s: io/db/npmysql.c.s
.PHONY : io/db/npmysql.s

# target to generate assembly for a file
io/db/npmysql.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/db/npmysql.c.s
.PHONY : io/db/npmysql.c.s

io/file/npcsv.o: io/file/npcsv.c.o
.PHONY : io/file/npcsv.o

# target to build an object file
io/file/npcsv.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npcsv.c.o
.PHONY : io/file/npcsv.c.o

io/file/npcsv.i: io/file/npcsv.c.i
.PHONY : io/file/npcsv.i

# target to preprocess a source file
io/file/npcsv.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npcsv.c.i
.PHONY : io/file/npcsv.c.i

io/file/npcsv.s: io/file/npcsv.c.s
.PHONY : io/file/npcsv.s

# target to generate assembly for a file
io/file/npcsv.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npcsv.c.s
.PHONY : io/file/npcsv.c.s

io/file/npgdal.o: io/file/npgdal.c.o
.PHONY : io/file/npgdal.o

# target to build an object file
io/file/npgdal.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npgdal.c.o
.PHONY : io/file/npgdal.c.o

io/file/npgdal.i: io/file/npgdal.c.i
.PHONY : io/file/npgdal.i

# target to preprocess a source file
io/file/npgdal.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npgdal.c.i
.PHONY : io/file/npgdal.c.i

io/file/npgdal.s: io/file/npgdal.c.s
.PHONY : io/file/npgdal.s

# target to generate assembly for a file
io/file/npgdal.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npgdal.c.s
.PHONY : io/file/npgdal.c.s

io/file/npjson.o: io/file/npjson.c.o
.PHONY : io/file/npjson.o

# target to build an object file
io/file/npjson.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npjson.c.o
.PHONY : io/file/npjson.c.o

io/file/npjson.i: io/file/npjson.c.i
.PHONY : io/file/npjson.i

# target to preprocess a source file
io/file/npjson.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npjson.c.i
.PHONY : io/file/npjson.c.i

io/file/npjson.s: io/file/npjson.c.s
.PHONY : io/file/npjson.s

# target to generate assembly for a file
io/file/npjson.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npjson.c.s
.PHONY : io/file/npjson.c.s

io/file/npkml.o: io/file/npkml.c.o
.PHONY : io/file/npkml.o

# target to build an object file
io/file/npkml.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npkml.c.o
.PHONY : io/file/npkml.c.o

io/file/npkml.i: io/file/npkml.c.i
.PHONY : io/file/npkml.i

# target to preprocess a source file
io/file/npkml.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npkml.c.i
.PHONY : io/file/npkml.c.i

io/file/npkml.s: io/file/npkml.c.s
.PHONY : io/file/npkml.s

# target to generate assembly for a file
io/file/npkml.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npkml.c.s
.PHONY : io/file/npkml.c.s

io/file/npobj.o: io/file/npobj.c.o
.PHONY : io/file/npobj.o

# target to build an object file
io/file/npobj.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npobj.c.o
.PHONY : io/file/npobj.c.o

io/file/npobj.i: io/file/npobj.c.i
.PHONY : io/file/npobj.i

# target to preprocess a source file
io/file/npobj.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npobj.c.i
.PHONY : io/file/npobj.c.i

io/file/npobj.s: io/file/npobj.c.s
.PHONY : io/file/npobj.s

# target to generate assembly for a file
io/file/npobj.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npobj.c.s
.PHONY : io/file/npobj.c.s

io/file/npxml.o: io/file/npxml.c.o
.PHONY : io/file/npxml.o

# target to build an object file
io/file/npxml.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npxml.c.o
.PHONY : io/file/npxml.c.o

io/file/npxml.i: io/file/npxml.c.i
.PHONY : io/file/npxml.i

# target to preprocess a source file
io/file/npxml.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npxml.c.i
.PHONY : io/file/npxml.c.i

io/file/npxml.s: io/file/npxml.c.s
.PHONY : io/file/npxml.s

# target to generate assembly for a file
io/file/npxml.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/file/npxml.c.s
.PHONY : io/file/npxml.c.s

io/gl/npgeometry.o: io/gl/npgeometry.c.o
.PHONY : io/gl/npgeometry.o

# target to build an object file
io/gl/npgeometry.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/npgeometry.c.o
.PHONY : io/gl/npgeometry.c.o

io/gl/npgeometry.i: io/gl/npgeometry.c.i
.PHONY : io/gl/npgeometry.i

# target to preprocess a source file
io/gl/npgeometry.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/npgeometry.c.i
.PHONY : io/gl/npgeometry.c.i

io/gl/npgeometry.s: io/gl/npgeometry.c.s
.PHONY : io/gl/npgeometry.s

# target to generate assembly for a file
io/gl/npgeometry.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/npgeometry.c.s
.PHONY : io/gl/npgeometry.c.s

io/gl/npgldraw.o: io/gl/npgldraw.c.o
.PHONY : io/gl/npgldraw.o

# target to build an object file
io/gl/npgldraw.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/npgldraw.c.o
.PHONY : io/gl/npgldraw.c.o

io/gl/npgldraw.i: io/gl/npgldraw.c.i
.PHONY : io/gl/npgldraw.i

# target to preprocess a source file
io/gl/npgldraw.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/npgldraw.c.i
.PHONY : io/gl/npgldraw.c.i

io/gl/npgldraw.s: io/gl/npgldraw.c.s
.PHONY : io/gl/npgldraw.s

# target to generate assembly for a file
io/gl/npgldraw.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/npgldraw.c.s
.PHONY : io/gl/npgldraw.c.s

io/gl/nptags.o: io/gl/nptags.c.o
.PHONY : io/gl/nptags.o

# target to build an object file
io/gl/nptags.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/nptags.c.o
.PHONY : io/gl/nptags.c.o

io/gl/nptags.i: io/gl/nptags.c.i
.PHONY : io/gl/nptags.i

# target to preprocess a source file
io/gl/nptags.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/nptags.c.i
.PHONY : io/gl/nptags.c.i

io/gl/nptags.s: io/gl/nptags.c.s
.PHONY : io/gl/nptags.s

# target to generate assembly for a file
io/gl/nptags.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/nptags.c.s
.PHONY : io/gl/nptags.c.s

io/gl/nptexmap.o: io/gl/nptexmap.c.o
.PHONY : io/gl/nptexmap.o

# target to build an object file
io/gl/nptexmap.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/nptexmap.c.o
.PHONY : io/gl/nptexmap.c.o

io/gl/nptexmap.i: io/gl/nptexmap.c.i
.PHONY : io/gl/nptexmap.i

# target to preprocess a source file
io/gl/nptexmap.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/nptexmap.c.i
.PHONY : io/gl/nptexmap.c.i

io/gl/nptexmap.s: io/gl/nptexmap.c.s
.PHONY : io/gl/nptexmap.s

# target to generate assembly for a file
io/gl/nptexmap.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/gl/nptexmap.c.s
.PHONY : io/gl/nptexmap.c.s

io/npch.o: io/npch.c.o
.PHONY : io/npch.o

# target to build an object file
io/npch.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npch.c.o
.PHONY : io/npch.c.o

io/npch.i: io/npch.c.i
.PHONY : io/npch.i

# target to preprocess a source file
io/npch.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npch.c.i
.PHONY : io/npch.c.i

io/npch.s: io/npch.c.s
.PHONY : io/npch.s

# target to generate assembly for a file
io/npch.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npch.c.s
.PHONY : io/npch.c.s

io/npdb.o: io/npdb.c.o
.PHONY : io/npdb.o

# target to build an object file
io/npdb.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npdb.c.o
.PHONY : io/npdb.c.o

io/npdb.i: io/npdb.c.i
.PHONY : io/npdb.i

# target to preprocess a source file
io/npdb.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npdb.c.i
.PHONY : io/npdb.c.i

io/npdb.s: io/npdb.c.s
.PHONY : io/npdb.s

# target to generate assembly for a file
io/npdb.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npdb.c.s
.PHONY : io/npdb.c.s

io/npfile.o: io/npfile.c.o
.PHONY : io/npfile.o

# target to build an object file
io/npfile.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npfile.c.o
.PHONY : io/npfile.c.o

io/npfile.i: io/npfile.c.i
.PHONY : io/npfile.i

# target to preprocess a source file
io/npfile.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npfile.c.i
.PHONY : io/npfile.c.i

io/npfile.s: io/npfile.c.s
.PHONY : io/npfile.s

# target to generate assembly for a file
io/npfile.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npfile.c.s
.PHONY : io/npfile.c.s

io/npgl.o: io/npgl.c.o
.PHONY : io/npgl.o

# target to build an object file
io/npgl.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npgl.c.o
.PHONY : io/npgl.c.o

io/npgl.i: io/npgl.c.i
.PHONY : io/npgl.i

# target to preprocess a source file
io/npgl.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npgl.c.i
.PHONY : io/npgl.c.i

io/npgl.s: io/npgl.c.s
.PHONY : io/npgl.s

# target to generate assembly for a file
io/npgl.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npgl.c.s
.PHONY : io/npgl.c.s

io/npglut.o: io/npglut.c.o
.PHONY : io/npglut.o

# target to build an object file
io/npglut.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npglut.c.o
.PHONY : io/npglut.c.o

io/npglut.i: io/npglut.c.i
.PHONY : io/npglut.i

# target to preprocess a source file
io/npglut.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npglut.c.i
.PHONY : io/npglut.c.i

io/npglut.s: io/npglut.c.s
.PHONY : io/npglut.s

# target to generate assembly for a file
io/npglut.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npglut.c.s
.PHONY : io/npglut.c.s

io/npkey.o: io/npkey.c.o
.PHONY : io/npkey.o

# target to build an object file
io/npkey.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npkey.c.o
.PHONY : io/npkey.c.o

io/npkey.i: io/npkey.c.i
.PHONY : io/npkey.i

# target to preprocess a source file
io/npkey.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npkey.c.i
.PHONY : io/npkey.c.i

io/npkey.s: io/npkey.c.s
.PHONY : io/npkey.s

# target to generate assembly for a file
io/npkey.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npkey.c.s
.PHONY : io/npkey.c.s

io/npmouse.o: io/npmouse.c.o
.PHONY : io/npmouse.o

# target to build an object file
io/npmouse.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npmouse.c.o
.PHONY : io/npmouse.c.o

io/npmouse.i: io/npmouse.c.i
.PHONY : io/npmouse.i

# target to preprocess a source file
io/npmouse.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npmouse.c.i
.PHONY : io/npmouse.c.i

io/npmouse.s: io/npmouse.c.s
.PHONY : io/npmouse.s

# target to generate assembly for a file
io/npmouse.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/io/npmouse.c.s
.PHONY : io/npmouse.c.s

lib/soil/src/SOIL.o: lib/soil/src/SOIL.c.o
.PHONY : lib/soil/src/SOIL.o

# target to build an object file
lib/soil/src/SOIL.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/SOIL.c.o
.PHONY : lib/soil/src/SOIL.c.o

lib/soil/src/SOIL.i: lib/soil/src/SOIL.c.i
.PHONY : lib/soil/src/SOIL.i

# target to preprocess a source file
lib/soil/src/SOIL.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/SOIL.c.i
.PHONY : lib/soil/src/SOIL.c.i

lib/soil/src/SOIL.s: lib/soil/src/SOIL.c.s
.PHONY : lib/soil/src/SOIL.s

# target to generate assembly for a file
lib/soil/src/SOIL.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/SOIL.c.s
.PHONY : lib/soil/src/SOIL.c.s

lib/soil/src/image_DXT.o: lib/soil/src/image_DXT.c.o
.PHONY : lib/soil/src/image_DXT.o

# target to build an object file
lib/soil/src/image_DXT.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/image_DXT.c.o
.PHONY : lib/soil/src/image_DXT.c.o

lib/soil/src/image_DXT.i: lib/soil/src/image_DXT.c.i
.PHONY : lib/soil/src/image_DXT.i

# target to preprocess a source file
lib/soil/src/image_DXT.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/image_DXT.c.i
.PHONY : lib/soil/src/image_DXT.c.i

lib/soil/src/image_DXT.s: lib/soil/src/image_DXT.c.s
.PHONY : lib/soil/src/image_DXT.s

# target to generate assembly for a file
lib/soil/src/image_DXT.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/image_DXT.c.s
.PHONY : lib/soil/src/image_DXT.c.s

lib/soil/src/image_helper.o: lib/soil/src/image_helper.c.o
.PHONY : lib/soil/src/image_helper.o

# target to build an object file
lib/soil/src/image_helper.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/image_helper.c.o
.PHONY : lib/soil/src/image_helper.c.o

lib/soil/src/image_helper.i: lib/soil/src/image_helper.c.i
.PHONY : lib/soil/src/image_helper.i

# target to preprocess a source file
lib/soil/src/image_helper.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/image_helper.c.i
.PHONY : lib/soil/src/image_helper.c.i

lib/soil/src/image_helper.s: lib/soil/src/image_helper.c.s
.PHONY : lib/soil/src/image_helper.s

# target to generate assembly for a file
lib/soil/src/image_helper.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/image_helper.c.s
.PHONY : lib/soil/src/image_helper.c.s

lib/soil/src/stb_image_aug.o: lib/soil/src/stb_image_aug.c.o
.PHONY : lib/soil/src/stb_image_aug.o

# target to build an object file
lib/soil/src/stb_image_aug.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/stb_image_aug.c.o
.PHONY : lib/soil/src/stb_image_aug.c.o

lib/soil/src/stb_image_aug.i: lib/soil/src/stb_image_aug.c.i
.PHONY : lib/soil/src/stb_image_aug.i

# target to preprocess a source file
lib/soil/src/stb_image_aug.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/stb_image_aug.c.i
.PHONY : lib/soil/src/stb_image_aug.c.i

lib/soil/src/stb_image_aug.s: lib/soil/src/stb_image_aug.c.s
.PHONY : lib/soil/src/stb_image_aug.s

# target to generate assembly for a file
lib/soil/src/stb_image_aug.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/lib/soil/src/stb_image_aug.c.s
.PHONY : lib/soil/src/stb_image_aug.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/main.c.s
.PHONY : main.c.s

npctrl.o: npctrl.c.o
.PHONY : npctrl.o

# target to build an object file
npctrl.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npctrl.c.o
.PHONY : npctrl.c.o

npctrl.i: npctrl.c.i
.PHONY : npctrl.i

# target to preprocess a source file
npctrl.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npctrl.c.i
.PHONY : npctrl.c.i

npctrl.s: npctrl.c.s
.PHONY : npctrl.s

# target to generate assembly for a file
npctrl.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npctrl.c.s
.PHONY : npctrl.c.s

npdata.o: npdata.c.o
.PHONY : npdata.o

# target to build an object file
npdata.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npdata.c.o
.PHONY : npdata.c.o

npdata.i: npdata.c.i
.PHONY : npdata.i

# target to preprocess a source file
npdata.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npdata.c.i
.PHONY : npdata.c.i

npdata.s: npdata.c.s
.PHONY : npdata.s

# target to generate assembly for a file
npdata.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npdata.c.s
.PHONY : npdata.c.s

npio.o: npio.c.o
.PHONY : npio.o

# target to build an object file
npio.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npio.c.o
.PHONY : npio.c.o

npio.i: npio.c.i
.PHONY : npio.i

# target to preprocess a source file
npio.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npio.c.i
.PHONY : npio.c.i

npio.s: npio.c.s
.PHONY : npio.s

# target to generate assembly for a file
npio.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/npio.c.s
.PHONY : npio.c.s

os/linux/nplinux.o: os/linux/nplinux.c.o
.PHONY : os/linux/nplinux.o

# target to build an object file
os/linux/nplinux.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/linux/nplinux.c.o
.PHONY : os/linux/nplinux.c.o

os/linux/nplinux.i: os/linux/nplinux.c.i
.PHONY : os/linux/nplinux.i

# target to preprocess a source file
os/linux/nplinux.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/linux/nplinux.c.i
.PHONY : os/linux/nplinux.c.i

os/linux/nplinux.s: os/linux/nplinux.c.s
.PHONY : os/linux/nplinux.s

# target to generate assembly for a file
os/linux/nplinux.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/linux/nplinux.c.s
.PHONY : os/linux/nplinux.c.s

os/msw/npmsw.o: os/msw/npmsw.c.o
.PHONY : os/msw/npmsw.o

# target to build an object file
os/msw/npmsw.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/msw/npmsw.c.o
.PHONY : os/msw/npmsw.c.o

os/msw/npmsw.i: os/msw/npmsw.c.i
.PHONY : os/msw/npmsw.i

# target to preprocess a source file
os/msw/npmsw.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/msw/npmsw.c.i
.PHONY : os/msw/npmsw.c.i

os/msw/npmsw.s: os/msw/npmsw.c.s
.PHONY : os/msw/npmsw.s

# target to generate assembly for a file
os/msw/npmsw.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/msw/npmsw.c.s
.PHONY : os/msw/npmsw.c.s

os/npos.o: os/npos.c.o
.PHONY : os/npos.o

# target to build an object file
os/npos.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/npos.c.o
.PHONY : os/npos.c.o

os/npos.i: os/npos.c.i
.PHONY : os/npos.i

# target to preprocess a source file
os/npos.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/npos.c.i
.PHONY : os/npos.c.i

os/npos.s: os/npos.c.s
.PHONY : os/npos.s

# target to generate assembly for a file
os/npos.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/npos.c.s
.PHONY : os/npos.c.s

os/osx/nposx.o: os/osx/nposx.c.o
.PHONY : os/osx/nposx.o

# target to build an object file
os/osx/nposx.c.o:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/osx/nposx.c.o
.PHONY : os/osx/nposx.c.o

os/osx/nposx.i: os/osx/nposx.c.i
.PHONY : os/osx/nposx.i

# target to preprocess a source file
os/osx/nposx.c.i:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/osx/nposx.c.i
.PHONY : os/osx/nposx.c.i

os/osx/nposx.s: os/osx/nposx.c.s
.PHONY : os/osx/nposx.s

# target to generate assembly for a file
os/osx/nposx.c.s:
	$(MAKE) -f CMakeFiles/antz.dir/build.make CMakeFiles/antz.dir/os/osx/nposx.c.s
.PHONY : os/osx/nposx.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... antz"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ctrl/npcmd.o"
	@echo "... ctrl/npcmd.i"
	@echo "... ctrl/npcmd.s"
	@echo "... ctrl/npengine.o"
	@echo "... ctrl/npengine.i"
	@echo "... ctrl/npengine.s"
	@echo "... ctrl/nptest.o"
	@echo "... ctrl/nptest.i"
	@echo "... ctrl/nptest.s"
	@echo "... data/npmap.o"
	@echo "... data/npmap.i"
	@echo "... data/npmap.s"
	@echo "... data/npmapfile.o"
	@echo "... data/npmapfile.i"
	@echo "... data/npmapfile.s"
	@echo "... data/npnode.o"
	@echo "... data/npnode.i"
	@echo "... data/npnode.s"
	@echo "... io/db/npauxdb.o"
	@echo "... io/db/npauxdb.i"
	@echo "... io/db/npauxdb.s"
	@echo "... io/db/npmysql.o"
	@echo "... io/db/npmysql.i"
	@echo "... io/db/npmysql.s"
	@echo "... io/file/npcsv.o"
	@echo "... io/file/npcsv.i"
	@echo "... io/file/npcsv.s"
	@echo "... io/file/npgdal.o"
	@echo "... io/file/npgdal.i"
	@echo "... io/file/npgdal.s"
	@echo "... io/file/npjson.o"
	@echo "... io/file/npjson.i"
	@echo "... io/file/npjson.s"
	@echo "... io/file/npkml.o"
	@echo "... io/file/npkml.i"
	@echo "... io/file/npkml.s"
	@echo "... io/file/npobj.o"
	@echo "... io/file/npobj.i"
	@echo "... io/file/npobj.s"
	@echo "... io/file/npxml.o"
	@echo "... io/file/npxml.i"
	@echo "... io/file/npxml.s"
	@echo "... io/gl/npgeometry.o"
	@echo "... io/gl/npgeometry.i"
	@echo "... io/gl/npgeometry.s"
	@echo "... io/gl/npgldraw.o"
	@echo "... io/gl/npgldraw.i"
	@echo "... io/gl/npgldraw.s"
	@echo "... io/gl/nptags.o"
	@echo "... io/gl/nptags.i"
	@echo "... io/gl/nptags.s"
	@echo "... io/gl/nptexmap.o"
	@echo "... io/gl/nptexmap.i"
	@echo "... io/gl/nptexmap.s"
	@echo "... io/npch.o"
	@echo "... io/npch.i"
	@echo "... io/npch.s"
	@echo "... io/npdb.o"
	@echo "... io/npdb.i"
	@echo "... io/npdb.s"
	@echo "... io/npfile.o"
	@echo "... io/npfile.i"
	@echo "... io/npfile.s"
	@echo "... io/npgl.o"
	@echo "... io/npgl.i"
	@echo "... io/npgl.s"
	@echo "... io/npglut.o"
	@echo "... io/npglut.i"
	@echo "... io/npglut.s"
	@echo "... io/npkey.o"
	@echo "... io/npkey.i"
	@echo "... io/npkey.s"
	@echo "... io/npmouse.o"
	@echo "... io/npmouse.i"
	@echo "... io/npmouse.s"
	@echo "... lib/soil/src/SOIL.o"
	@echo "... lib/soil/src/SOIL.i"
	@echo "... lib/soil/src/SOIL.s"
	@echo "... lib/soil/src/image_DXT.o"
	@echo "... lib/soil/src/image_DXT.i"
	@echo "... lib/soil/src/image_DXT.s"
	@echo "... lib/soil/src/image_helper.o"
	@echo "... lib/soil/src/image_helper.i"
	@echo "... lib/soil/src/image_helper.s"
	@echo "... lib/soil/src/stb_image_aug.o"
	@echo "... lib/soil/src/stb_image_aug.i"
	@echo "... lib/soil/src/stb_image_aug.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... npctrl.o"
	@echo "... npctrl.i"
	@echo "... npctrl.s"
	@echo "... npdata.o"
	@echo "... npdata.i"
	@echo "... npdata.s"
	@echo "... npio.o"
	@echo "... npio.i"
	@echo "... npio.s"
	@echo "... os/linux/nplinux.o"
	@echo "... os/linux/nplinux.i"
	@echo "... os/linux/nplinux.s"
	@echo "... os/msw/npmsw.o"
	@echo "... os/msw/npmsw.i"
	@echo "... os/msw/npmsw.s"
	@echo "... os/npos.o"
	@echo "... os/npos.i"
	@echo "... os/npos.s"
	@echo "... os/osx/nposx.o"
	@echo "... os/osx/nposx.i"
	@echo "... os/osx/nposx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

